export const filas = [
    {
        producto: "Mangoes",
        cantidad: 420,
        precio: 3.5,
        tienda: "Frutería Wellington Q",
        notas: "Manguito Maracatón",
        comprado: true,
        imagen: "https://media.istockphoto.com/id/529964085/es/foto/mango.jpg?s=612x612&w=0&k=20&c=QyDy4ZpSZXUWgxdPrDIUMo-Rt6-fXPy_BH8_6piXmbk=",
    },
    {
        producto: "Leche",
        cantidad: 1,
        precio: 1,
        tienda: "Tienda de leche",
        notas: "Leche de avena",
        comprado: false,
        imagen: "https://www.marthastewart.com/thmb/b8VZ9AzhdfSQ4feJgPDHixCRTRg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/almond-milk-158-d112257_vert-e0733617724b430ab3827da93570f1f0.jpg",
    },
    {
        producto: "Pan",
        cantidad: 1,
        precio: 25,
        tienda: "Tienda de cocina",
        notas: "En inglés",
        comprado: true,
        imagen: "https://www.ikea.com/es/en/images/products/hemlagad-frying-pan-black__0789104_pe763825_s5.jpg",
    },
    {
        producto: "WebOS",
        cantidad: 5,
        precio: 399,
        tienda: "LG",
        notas: "Sistema Operativo WebOS",
        comprado: true,
        imagen: "https://www.webosose.org/images/webOS_OSE_logo.jpg",
    },
    {
        producto: "Pollo Tikka Masala",
        cantidad: 13,
        precio: 12,
        tienda: "Restaurante Indú",
        notas: "La receta es Británica",
        comprado: false,
        imagen: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/chicken-tikka-masala.jpg",
    },
    {
        producto: "Tomates",
        cantidad: 7,
        precio: 0,
        tienda: "Frutería F",
        notas: "Tomates sintéticos",
        comprado: true,
        imagen: "https://trackercdn.com/legacycdn/fortnite/20BA4836_large.png",
    },
    {
        producto: "Walter",
        cantidad: 1,
        precio: 1,
        tienda: "Mercado Mr.White",
        notas: "Walter",
        comprado: false,
        imagen: "https://adrianheca.github.io/LMGI/Actividad_4/Walter.jpg",
    },
];